### ISSUE TITLE
Compatibility issue with pytest >= 3

### ISSUE THREAD

**Issue by ncoghlan** [ribozz/behave-pytest#2]
Hi, thanks for writing this, it's been very helpful!

However, it seems the `_pytest` internals it relies on have changed in the latest release:

    Traceback (most recent call last):
      ... <snip behave machinery> ...
      File "features/environment.py", line 156, in before_all
        install_pytest_asserts()
      File "/home/ncoghlan/.virtualenvs/bayesian/lib/python3.5/site-packages/behave_pytest/hook.py", line 21, in install_pytest_asserts
        from _pytest.assertion import reinterpret  # noqa
    ImportError: cannot import name 'reinterpret'

This looks to be the relevant pytest 3.0 change: https://github.com/pytest-dev/pytest/pull/1733/files
And there's some discussion of the change here: https://mail.python.org/pipermail/pytest-dev/2016-April/003540.html

As an interim workaround, changing our testing dependencies to `pytest < 3` gets things working again, but a better fix would likely be to remove the installation of the reinterpretation hook from `behave_pytest` as well - I'll submit a PR for that.

**Comment by ncoghlan** [comment]
PR: https://github.com/ribozz/behave-pytest/pull/3

**Comment by ncoghlan** [comment]
Investigating the problem further, it looks like the assertion rewriting wasn't triggering at all for behave step definitions, so the improved error messages were coming entirely from the now removed "reinterpret.AssertionError". Accordingly, a better fix might be to just bring that code wholesale into this project.

**Comment by ncoghlan** [comment]
Specifically, this is the module that was dropped from `pytest` that the `behave` integration was relying on: https://github.com/pytest-dev/pytest/blob/ee374e3b8059351719a85fa3ba7abd5ec6b632ea/_pytest/assertion/reinterpret.py

**Comment by nicoddemus** [comment]
Hi,

I landed here from @hackebrot's tweet. 😁 

As discussed on the links, reinterpret was removed because it could produce weird side-effects. Pytest 3.0 and onward only supports assertion rewriting.

I don't know `behave-pytest`, but you can mark some modules for assertion rewriting by calling [`register_assert_rewrite`](http://doc.pytest.org/en/latest/writing_plugins.html?highlight=register_assert_rewrite#pytest.register_assert_rewrite). This is called automatically on packages which are registered as setuptools plugins, which as far as I can see is not the case for `behave-pytest`, but I'm not sure if it will help out in your situation.

**Comment by ncoghlan** [comment]
Aye, I was able to get the rewriting hook installed via:

    def install_pytest_asserts():
        import _pytest.config
        import _pytest.assertion
        config = _pytest.config._prepareconfig([], [])
        _pytest.assertion.install_importhook(config)

(Still fiddling with private APIs, but if it had worked, tidy enough I would have submitted an RFE for a public API along those lines)

However, @bkabrda was able to figure out why that *doesn't* work, `behave` (by design) doesn't rely on the import system (with all its side effects) to load the step code: https://github.com/behave/behave/blob/master/behave/runner.py#L354

So here's our current monkeypatching approach:

    ### make sure behave uses pytest improved asserts
    # Behave runner uses behave.runner.exec_file function to read, compile
    # and exec code of environment file and step files *in this order*.
    # Therefore we provide a new implementation here, which uses pytest's
    # _pytest.assertion.rewrite to rewrite the bytecode with pytest's
    # improved asserts.
    # This means that when behave tries to load steps, it will use our exec_file.
    # => SUCCESS
    import behave.runner

    def exec_file(filename, globals={}, locals=None):
        if locals is None:
            locals = globals
        locals['__file__'] = filename
        from py import path
        from _pytest import config
        from _pytest.assertion import rewrite
        f = path.local(filename)
        filename2 = os.path.relpath(filename, os.getcwd())
        config = config._prepareconfig([], [])
        _, code = rewrite._rewrite_test(config, f)
        exec(code, globals, locals)

    behave.runner.exec_file = exec_file
    ### end monkeypatch

Which does what we need, but only by accessing private APIs in pytest, and monkeypatching them in behave. Figuring out how to turn that it into maintainable RFEs for both projects is going to be... interesting.

**Comment by nicoddemus** [comment]
Glad you guys were able to figure this out! 😁

**Comment by bittner** [comment]
Does [that](https://github.com/ribozz/behave-pytest/issues/2#issuecomment-258448045) mean we're not going to get pytest-style assertions in behave in the foreseeable future?

Is there any chance to make this work with behave in a viable, conformant way (i.e. install a package with pip, and you're done)? Maybe change the behave internals, open up behave, have an appropriate API for this? @jenisys?
